#include "homepage_repository.hpp"
#include <pqxx/pqxx>

namespace { bool terminal(const std::string& status){return status=="SUCCEEDED"||status=="FAILED"||status=="CANCELLED";} }
ClaimResult HomePageRepository::claim(const StreamMessage& message) const{
  pqxx::connection connection(config_.database_url); pqxx::work tx(connection);
  const auto rows=tx.exec_params(R"SQL(UPDATE "HomePageGenerationTask" SET status='RUNNING',attempts=attempts+1,"workerId"=$2,"fencingToken"="fencingToken"+1,"leaseExpiresAt"=NOW()+($3*INTERVAL '1 second'),"heartbeatAt"=NOW(),"nextAttemptAt"=NULL,"startedAt"=COALESCE("startedAt",NOW()),"updatedAt"=NOW() WHERE id=$1 AND (((status='PENDING' OR status='RETRY_WAIT') AND ("nextAttemptAt" IS NULL OR "nextAttemptAt"<=NOW())) OR (status='RUNNING' AND ("leaseExpiresAt" IS NULL OR "leaseExpiresAt"<=NOW()))) RETURNING "selectionJson"::text,"fencingToken",attempts)SQL",message.run_id,config_.worker_id,config_.lease_seconds);
  if(!rows.empty()){RunTask task{message,rows[0][1].as<std::int64_t>(),rows[0][2].as<int>(),nlohmann::json::parse(rows[0][0].as<std::string>())};tx.commit();return{ClaimStatus::claimed,std::move(task)};}
  const auto state=tx.exec_params(R"SQL(SELECT status::text FROM "HomePageGenerationTask" WHERE id=$1)SQL",message.run_id);tx.commit(); if(state.empty())return{ClaimStatus::missing,{}}; return{terminal(state[0][0].as<std::string>())?ClaimStatus::terminal:ClaimStatus::busy,{}};
}
std::vector<std::pair<std::string,std::int64_t>> HomePageRepository::heartbeat(const std::vector<std::pair<std::string,std::int64_t>>& leases) const{std::vector<std::pair<std::string,std::int64_t>> renewed;if(leases.empty())return renewed;pqxx::connection connection(config_.database_url);pqxx::work tx(connection);for(const auto&[id,token]:leases){auto result=tx.exec_params(R"SQL(UPDATE "HomePageGenerationTask" SET "heartbeatAt"=NOW(),"leaseExpiresAt"=NOW()+($3*INTERVAL '1 second'),"updatedAt"=NOW() WHERE id=$1 AND "fencingToken"=$2 AND status='RUNNING')SQL",id,token,config_.lease_seconds);if(result.affected_rows()==1)renewed.emplace_back(id,token);}tx.commit();return renewed;}
bool HomePageRepository::schedule_retry(const RunTask& task,const WorkerError& error,int delay) const{pqxx::connection connection(config_.database_url);pqxx::work tx(connection);auto result=tx.exec_params(R"SQL(UPDATE "HomePageGenerationTask" SET status='RETRY_WAIT',"nextAttemptAt"=NOW()+($5*INTERVAL '1 second'),"eventPublishedAt"=NULL,"errorCode"=$3,"errorMessage"=$4,"workerId"=NULL,"leaseExpiresAt"=NULL,"updatedAt"=NOW() WHERE id=$1 AND "fencingToken"=$2 AND status='RUNNING')SQL",task.message.run_id,task.fencing_token,error.code(),error.what(),delay);tx.commit();return result.affected_rows()==1;}
bool HomePageRepository::mark_failed(const RunTask& task,const WorkerError& error) const{pqxx::connection connection(config_.database_url);pqxx::work tx(connection);const std::string status=error.code()=="STALE_GENERATION_TASK"?"CANCELLED":"FAILED";auto result=tx.exec_params(R"SQL(UPDATE "HomePageGenerationTask" SET status=$3::"HomePageGenerationTaskStatus","errorCode"=$4,"errorMessage"=$5,"workerId"=NULL,"leaseExpiresAt"=NULL,"completedAt"=NOW(),"updatedAt"=NOW() WHERE id=$1 AND "fencingToken"=$2 AND status='RUNNING')SQL",task.message.run_id,task.fencing_token,status,error.code(),error.what());tx.commit();return result.affected_rows()==1;}
void HomePageRepository::commit_result(const RunTask& task,const HomePageGenerationResult& result) const{pqxx::connection connection(config_.database_url);pqxx::work tx(connection);const auto locked=tx.exec_params(R"SQL(SELECT id FROM "HomePageGenerationTask" WHERE id=$1 AND "fencingToken"=$2 AND status='RUNNING' FOR UPDATE)SQL",task.message.run_id,task.fencing_token);if(locked.empty())throw WorkerError("LEASE_LOST","提交快照前 lease 已失效",true);tx.exec_params(R"SQL(INSERT INTO "HomePageSnapshot"(id,scope,"userId","preferenceFingerprint","baselineDefaultSnapshotId",payload,"dataAsOf","generatedAt","generationTaskId") SELECT id,scope,"userId","preferenceFingerprint","baselineDefaultSnapshotId",$3::jsonb,$4,NOW(),id FROM "HomePageGenerationTask" WHERE id=$1 AND "fencingToken"=$2 AND status='RUNNING' ON CONFLICT("generationTaskId") DO NOTHING)SQL",task.message.run_id,task.fencing_token,result.payload.dump(),result.data_as_of);auto updated=tx.exec_params(R"SQL(UPDATE "HomePageGenerationTask" SET status='SUCCEEDED',"errorCode"=NULL,"errorMessage"=NULL,"workerId"=NULL,"leaseExpiresAt"=NULL,"completedAt"=NOW(),"updatedAt"=NOW() WHERE id=$1 AND "fencingToken"=$2 AND status='RUNNING')SQL",task.message.run_id,task.fencing_token);if(updated.affected_rows()!=1)throw WorkerError("LEASE_LOST","提交终态时 lease 已失效",true);tx.commit();}
bool HomePageRepository::ping() const{try{pqxx::connection connection(config_.database_url);pqxx::read_transaction tx(connection);return tx.exec("SELECT 1")[0][0].as<int>()==1;}catch(...){return false;}}
